### PR TITLE
Fix the test case.

### PR DESCRIPTION
**Pull request by VeerMuchandi**
Assert.assertEquals("Hello, World!", message.getContent()); 
should be changed to 
Assert.assertEquals("Hello, World", message.getContent()); 

Remove "!"as the message displayed is "Hello, World"

### CODE REVIEW

**Comment by gytis** [comment]
Are you sure? Configuration has an exclamation mark: https://github.com/VeerMuchandi/springboot-testsuite/blob/9f5ce7d28906cdf1a8f0eb9f96aca29a0bb96f64/rest/src/main/resources/application.properties#L1

**Comment by VeerMuchandi** [comment]
I tested it by cloning the repo locally. The test case failed and that is
how I fixed it.

**Comment by gytis** [comment]
Test passes for me as is. Here's the response I get if i run the application: {"id":1,"content":"Hello, World!"}.
@cmoulliard, could you double check on your machine just in case?

**Comment by cmoulliard** [comment]
local test is working fine for me --> `mvn clean install`. So I will decline this PR.

**Comment by VeerMuchandi** [comment]
Does the frontend generator use the same code or different?

On Tue, Mar 7, 2017 at 11:39 AM, Charles Moulliard <notifications@github.com

**Comment by gytis** [comment]
Generator uses quickstarts from here: https://github.com/obsidian-toaster-quickstarts.

**Pull request closed without merging**
